#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8001
#          predicates:
#            - Path= /products/**
#        - id: r1
#          uri: http://localhost:8002
#          predicates:
#            - Path= /users/**